longitude = 6.57

[image]
umin = 1
umax = 200
scale = "3amin"
size = "2000 2000"

[vis_cube]
fov = 60
umin = 5
umax = 100
win_fct = "blackmanharris"

[power_spectra]
eor_bin_list = 'config/eor_bins.parset'
ps_config = 'config/ps_config_mwa.parset'
flagger = 'config/flagger.parset'

